"""Prompt templates for robot manipulation video annotation."""

from .vocabulary import (
    ACTION_VOCABULARY,
    ACTION_FINE_GRAINED_GUIDANCE,
    FEW_SHOT_EXAMPLES,
)
from .analysis import (
    ANALYSIS_SYSTEM_PROMPT,
    ANALYSIS_PROMPT_TEMPLATE,
)
from .refinement import (
    REFINEMENT_SYSTEM_PROMPT,
    REFINEMENT_PROMPT_TEMPLATE,
)
from .detail_refinement import (
    DETAIL_REFINEMENT_SYSTEM_PROMPT,
    DETAIL_REFINEMENT_PROMPT_TEMPLATE,
)
from .bimanual import (
    BIMANUAL_SUPPLEMENT,
    ANALYSIS_SYSTEM_PROMPT_BIMANUAL,
    REFINEMENT_SYSTEM_PROMPT_BIMANUAL,
    DETAIL_REFINEMENT_SYSTEM_PROMPT_BIMANUAL,
)
from .galaxea_step import (
    GALAXEA_STEP_SYSTEM_PROMPT,
    GALAXEA_STEP_SYSTEM_PROMPT_BIMANUAL,
    GALAXEA_STEP_PROMPT_TEMPLATE,
    DEDUP_STEPS_PROMPT,
)
from .robocoin import (
    ACTION_FINE_GRAINED_GUIDANCE_ROBOCOIN,
    GALAXEA_STEP_SYSTEM_PROMPT_BIMANUAL_ROBOCOIN,
    GALAXEA_STEP_PROMPT_TEMPLATE_ROBOCOIN,
)
