run_id: qwen35_OFT_aloha_multi_mix
run_root_dir: results/Checkpoints
seed: 42
trackers: [jsonl, wandb]
wandb_entity: rjucdvfh04
wandb_project: qwen35_OFT_aloha_multi_mix
is_debug: false

framework:
  name: QwenOFT
  qwenvl:
    base_vlm: /mnt/cpfs_m6_29eu38p1/data/shared/Group-m6/tongzai.hxt/Pretrained_models/Qwen3.5-4B
    attn_implementation: flash_attention_2
    vl_hidden_dim: 2560

  action_model:
    action_model_type: DiT-B
    action_hidden_dim: 2560
    action_dim: 14
    state_dim: 14
    future_action_window_size: 15
    action_horizon: 16
    past_action_window_size: 0
    hidden_size: 1024

datasets:
  vla_data:
    dataset_py: lerobot_datasets
    data_root_dir: /mnt/cpfs_m6_29eu38p1/data/shared/Group-m6/tongzai.hxt
    data_mix: aloha_multi_mix
    action_type: abs_joint
    default_image_resolution: [3, 224, 224]
    per_device_batch_size: 8
    obs: ["image_0", "image_1", "image_2"]
    image_size: [224, 224]
    lerobot_version: v2.0
    video_backend: pyav

trainer:
  epochs: 100
  max_train_steps: 200000
  num_warmup_steps: 5000
  save_interval: 10000
  eval_interval: 1000
  learning_rate:
    base: 2.0e-05
    qwen_vl_interface: 1.0e-05
    action_model: 1.0e-04
  lr_scheduler_type: cosine_with_min_lr
  scheduler_specific_kwargs:
    min_lr: 5.0e-07
  freeze_modules: ''
  loss_scale:
    vla: 1.0
    vlm: 0.1
  max_grad_norm: 1.0
  warmup_ratio: 0.1
  weight_decay: 0.0
  logging_frequency: 100
  gradient_clipping: 1.0
  gradient_accumulation_steps: 1

  optimizer:
    name: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-08
    weight_decay: 1.0e-08

  is_resume: false
  resume_epoch: null
  resume_step: null
  enable_gradient_checkpointing: true
  enable_mixed_precision_training: true
